version: "3"

services:
  # PostgreSQL
  db:
    container_name: postgres_db
    image: postgres:latest
    env_file: ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Django REST framework
  web:
    container_name: drf
    env_file: ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=aw_project.settings.prod_docker_postgres
    build: .
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn aw_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  # Nginx

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres-data:
    driver: local
