name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE_DEV_SQLITE }}
      
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

    - name: Create .env file from GitHub Secrets
      run: |
       echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
       echo DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE_PROD_DOCKER_POSTGRES }} >> .env
       echo DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} >> .env
       echo DJANGO_SUPERUSER_NAME=${{ secrets.DJANGO_SUPERUSER_NAME }} >> .env
       echo DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }} >> .env
       echo POSTGRES_ENGIN=${{ secrets.POSTGRES_ENGIN }} >> .env
       echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
       echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
       echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
       echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env

    - name: Docker Compose Up
      run: |
       docker-compose up -d

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u yurite6174 --password-stdin

    # Push to GHCR
    - name: Push to GitHub Container Registry
      run: |
        docker tag augmented-world-backend-api_nginx:latest ghcr.io/yurite6174/augmented-world-backend-api_nginx:latest
        docker tag augmented-world-backend-api_web:latest ghcr.io/yurite6174/augmented-world-backend-api_web:latest
        docker tag postgres:latest ghcr.io/yurite6174/postgres:latest
        docker push ghcr.io/yurite6174/backend-nginx:latest
        docker push ghcr.io/yurite6174/backend-web:latest
        docker push ghcr.io/yurite6174/postgres:latest

    - name: Deploy an App Engine app
      id: deploy-app
      uses: google-github-actions/deploy-appengine@v1
      with:
        project_id: ${{ secrets.GCE_PROJECT }}
        deliverables: app.yaml
        credentials: ${{ secrets.GCE_SA_KEY }}

